#!/bin/bash
# from http://wiki.bash-hackers.org/howto/getopts_tutorial
 
while getopts ":a:" opt; do
  case $opt in
    a)
      echo "-a was triggered, Parameter: $OPTARG" >&2
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

# getopt v.s. getopts
# http://aplawrence.com/Unix/getopts.html
