#!/bin/bash
# from http://wiki.bash-hackers.org/howto/getopts_tutorial

#if ! getopts ":a:" opt; then
#	echo "This script can get '-a' parameter"
#	exit 2
#fi
 
while getopts ":a:" opt; do
  case $opt in
    a)
      echo "-a was triggered, Parameter: $OPTARG" >&2
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done
shift $(($OPTIND - 1))
echo "$@"


# getopt v.s. getopts
# http://aplawrence.com/Unix/getopts.html
